/*categories ->  1: frontend, 2: model*/
const PHOTO_EDIT = '/f_auto,dpr_auto,q_auto:good'
const projectsDb = {
  portfolioList: [
    {
      id: 1,
      title: 'SCORM COURSES',
      description: 'UI/UX & Frontend development',
      cover:
        'https://res.cloudinary.com/ivanrice-c/image/upload/v1607464629/portfolio/uiux_courses/cover_qdqtrt.jpg',
      category: 1,
      tools: ['css', 'html', 'php', 'jquery', 'bootstrap'],
    },
    {
      id: 2,
      title: 'FILE MANAGER',
      description: 'Php - Angular fullstack development',
      cover:
        'https://res.cloudinary.com/ivanrice-c/image/upload/v1607457390/portfolio/register/cover_u2sfu8.jpg',
      category: 1,
      tools: ['angular', 'html', 'php', 'css', 'bootstrap', 'mysql'],
    },
    {
      id: 3,
      title: 'SCHOOL MANAGER',
      description: 'React - php fullstack development',
      cover:
        'https://res.cloudinary.com/ivanrice-c/image/upload/v1607459514/portfolio/sigem/cover_rzgzjm.jpg',
      category: 1,
      tools: ['react', 'html', 'php', 'css', 'bootstrap'],
    },
    {
      id: 4,
      title: 'VEHICLE INSURANCE',
      description: 'Webservice - lamp fullstack development',
      cover:
        'https://res.cloudinary.com/ivanrice-c/image/upload/v1607724480/portfolio/saas/cover_dhddwu.jpg',
      category: 1,
      tools: ['html', 'php', 'jquery', 'css', 'bootstrap', 'mysql'],
    },
    {
      id: 5,
      title: 'SPACE SHIP',
      description: 'A steampunk style & material practice',
      cover:
        'https://cdnb.artstation.com/p/assets/images/images/027/424/717/20200607002852/smaller_square/ivan-bautista-nave-final.jpg?1591507733',
      category: 2,
      tools: ['mari', 'nuke', 'rizom', 'maya', 'arnold', 'zbrush'],
    },
    {
      id: 6,
      title: 'CLANCY',
      description: 'Clancy fan art from The midnight gospel',
      cover:
        'https://cdna.artstation.com/p/assets/images/images/030/401/790/smaller_square/ivan-bautista-clancy-w.jpg',
      category: 2,
      tools: ['zbrush', 'maya', 'redshift', 'rizom'],
    },
    {
      id: 7,
      title: 'STILL LIFE',
      description: 'A practice of lighting and materials',
      cover:
        'https://cdna.artstation.com/p/assets/images/images/018/363/916/smaller_square/ivan-bautista-vasijas-final.jpg',
      category: 2,
      tools: ['substance', 'nuke', 'maya', 'arnold', 'rizom', 'mari'],
    },
    {
      id: 8,
      title: 'KID MOSTRO',
      description: 'A practice of fur grooming and lighting',
      cover:
        'https://cdnb.artstation.com/p/assets/images/images/018/831/139/smaller_square/ivan-bautista-kidmostro-camera1.jpg',
      category: 2,
      tools: ['mari', 'arnold', 'rizom', 'maya', 'zbrush', 'nuke'],
    },
    {
      id: 9,
      title: 'GRIM REAPER',
      description: 'The grim fan art from Billy & Mandy',
      cover:
        'https://cdnb.artstation.com/p/assets/images/images/018/378/367/smaller_square/ivan-bautista-huesos-final-smoke.jpg',
      category: 2,
      tools: ['rizom', 'arnold', 'nuke', 'mari', 'maya'],
    },
    {
      id: 10,
      title: 'REINHARDT',
      description: 'Reinhardt fan art from overwatch',
      cover:
        'https://cdnb.artstation.com/p/assets/images/images/018/364/081/smaller_square/ivan-bautista-final-rein.jpg',
      category: 2,
      tools: ['mari', 'arnold', 'substance', 'maya', 'rizom'],
    },
  ],
  img_items: [
    {
      id: 1,
      idPortfolioList: 1,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607465147/portfolio/uiux_courses/cover_intrd_tgr1wu.jpg`,
      alt: 'cover of the project: UI/UX and Frontend',
    },
    {
      id: 2,
      idPortfolioList: 1,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607464630/portfolio/uiux_courses/projectbr_eccsc5.jpg`,
      alt: 'brief of the project',
    },
    {
      id: 3,
      idPortfolioList: 1,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607464840/portfolio/uiux_courses/unam_courses_bauuzd.jpg`,
      alt: 'Unam course syllabus developed with html, css and javascript',
    },
    {
      id: 4,
      idPortfolioList: 1,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607464839/portfolio/uiux_courses/inbursa_ej4pxy.jpg`,
      alt: 'Inbursa course developed with html, css and javascript',
    },
    {
      id: 5,
      idPortfolioList: 1,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607464840/portfolio/uiux_courses/unam_mwhc4t.jpg`,
      alt: 'Unam course developed with html, css and javascript',
    },
    {
      id: 6,
      idPortfolioList: 1,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607464839/portfolio/uiux_courses/comex_kpclpp.jpg`,
      alt: 'Comex course login developed with html and css ',
    },
    {
      id: 7,
      idPortfolioList: 1,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607464629/portfolio/uiux_courses/3daovs_kodp4x.jpg`,
      alt: 'Render Screen title',
    },
    {
      id: 8,
      idPortfolioList: 1,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607464630/portfolio/uiux_courses/AOV_dt2usc.jpg`,
      alt: 'Render of background made in 3D',
    },
    {
      id: 1,
      idPortfolioList: 2,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607457388/portfolio/register/architecture_ziwkev.jpg`,
      alt: 'Architecture of the project: File Manager',
    },
    {
      id: 2,
      idPortfolioList: 2,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607457387/portfolio/register/about_hfuz4v.jpg`,
      alt: 'Brief of the project',
    },
    {
      id: 3,
      idPortfolioList: 2,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607457389/portfolio/register/colors_kenjw1.jpg`,
      alt: 'Color palette of the project',
    },
    {
      id: 4,
      idPortfolioList: 2,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607457391/portfolio/register/registro_nja0dq.jpg`,
      alt: 'Register and signin screen',
    },
    {
      id: 5,
      idPortfolioList: 2,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607457393/portfolio/register/ticket_k8uv7h.jpg`,
      alt: 'Receipt management screen',
    },
    {
      id: 6,
      idPortfolioList: 2,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607457393/portfolio/register/USER_xa4utd.jpg`,
      alt: 'User screen',
    },
    {
      id: 1,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607459337/portfolio/sigem/sigem_jmpwcl.jpg`,
      alt: 'Title of the project: sigem',
    },
    {
      id: 2,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607459327/portfolio/sigem/architectured_b5sv4j.jpg`,
      alt: 'Architecture of the project: School Manager',
    },
    {
      id: 3,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607459337/portfolio/sigem/about-1_a1iths.jpg`,
      alt: 'Project brief title',
    },
    {
      id: 4,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607459327/portfolio/sigem/about_b_widza1.jpg`,
      alt: 'Brief of the project screen',
    },
    {
      id: 5,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607459337/portfolio/sigem/wireframe_omb3fa.jpg`,
      alt: 'Wireframe title',
    },
    {
      id: 6,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607459320/portfolio/sigem/setup_xxb43u.jpg`,
      alt: 'Install wireframe screen',
    },
    {
      id: 7,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607459320/portfolio/sigem/campus_xqqaf8.jpg`,
      alt: 'CRUD campus wireframe screen',
    },
    {
      id: 8,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607459320/portfolio/sigem/home_hpevp4.jpg`,
      alt: 'Home wireframe screen',
    },
    {
      id: 9,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607459319/portfolio/sigem/user_menu_oi2kzn.jpg`,
      alt: 'User Menu Wireframe screen',
    },
    {
      id: 10,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607459320/portfolio/sigem/5users_f51yh5.jpg`,
      alt: 'User wireframe screen',
    },
    {
      id: 11,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607459320/portfolio/sigem/6calendar_fmrmef.jpg`,
      alt: 'School periods wireframe screen',
    },
    {
      id: 12,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607459337/portfolio/sigem/uiux_dashboard_jzdkfs.jpg`,
      alt: 'ui/ux - dashboards title',
    },
    {
      id: 13,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607459332/portfolio/sigem/dashboard_cvgrbu.jpg`,
      alt: 'Dashboard screen in multiple devices',
    },
    {
      id: 14,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607459337/portfolio/sigem/uiux_user_jy85su.jpg`,
      alt: 'ui/ux - user reporter',
    },
    {
      id: 15,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607459332/portfolio/sigem/USER_a9pczq.jpg`,
      alt: 'User reporter screen in multiple devices',
    },
    {
      id: 16,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607459337/portfolio/sigem/uiux_PDF_q0jz0e.jpg`,
      alt: 'ui/ux - pdf viewer title',
    },
    {
      id: 17,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607459332/portfolio/sigem/pdf_erwqsr.jpg`,
      alt: 'PDF viewer screen in multiple devices',
    },
    {
      id: 18,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607459337/portfolio/sigem/SIGEMV1_wfojau.jpg`,
      alt: 'sigem version 1 title',
    },
    {
      id: 19,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1607459327/portfolio/sigem/version1_ywzplo.jpg`,
      alt: 'Sigem version 1 screen',
    },
    {
      id: 1,
      idPortfolioList: 4,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606946296/portfolio/saas/1_architexture_y0ozna.png`,
      alt: 'Architecture of the project: saas consultores',
    },
    {
      id: 2,
      idPortfolioList: 4,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606946297/portfolio/saas/qwe_jekbcq.png`,
      alt: 'Project brief of the project',
    },
    {
      id: 3,
      idPortfolioList: 4,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606946296/portfolio/saas/3_color_cx99ka.png`,
      alt: 'Color pallete',
    },
    {
      id: 4,
      idPortfolioList: 4,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606946296/portfolio/saas/4_UIUX_gweaqf.png`,
      alt: 'ui/ux title',
    },
    {
      id: 5,
      idPortfolioList: 4,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606946297/portfolio/saas/portada_ptdqss.jpg`,
      alt: 'Login screen',
    },
    {
      id: 6,
      idPortfolioList: 4,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606946297/portfolio/saas/menu_g0dsid.jpg`,
      alt: 'Menu option',
    },
    {
      id: 7,
      idPortfolioList: 4,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606946296/portfolio/saas/cotizacion_shbwlb.jpg`,
      alt: 'quote a vehicle policy screen',
    },
    {
      id: 8,
      idPortfolioList: 4,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606946296/portfolio/saas/mensaje_hjigrw.jpg`,
      alt: 'Loading screen',
    },
    {
      id: 9,
      idPortfolioList: 4,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606946296/portfolio/saas/consulta_b3fgmm.jpg`,
      alt: 'Policies',
    },
    {
      id: 1,
      idPortfolioList: 5,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606775187/portfolio/model/nave-final_v6m09q.jpg`,
      alt: 'Steampunk spaceship',
    },
    {
      id: 2,
      idPortfolioList: 5,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606774993/portfolio/model/SPEC_dgjnox.jpg`,
      alt: '´Specular. Arbitrary output variable',
    },
    {
      id: 3,
      idPortfolioList: 5,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606774992/portfolio/model/DIFFUSE_bhdjqm.jpg`,
      alt: 'Diffuse color. Arbitrary output variable',
    },
    {
      id: 4,
      idPortfolioList: 5,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606774994/portfolio/model/emission_qyjzyw.jpg`,
      alt: 'Emission. Arbitrary output variable',
    },
    {
      id: 5,
      idPortfolioList: 5,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606774993/portfolio/model/LIGHT_uu7hiw.jpg`,
      alt: 'Lighting. Arbitrary output variable',
    },
    {
      id: 6,
      idPortfolioList: 5,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606774993/portfolio/model/UVMAP_utl350.jpg`,
      alt: 'Uv UDIMS',
    },
    {
      id: 7,
      idPortfolioList: 5,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606775523/portfolio/model/ivan-bautista-wip2_hd2o1r.jpg`,
      alt: 'Mari texture screeen',
    },
    {
      id: 1,
      idPortfolioList: 6,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606776535/portfolio/model/midnightgospel/final_img_c_mzsgrf.jpg`,
      alt: 'Clancy from midnight gospel',
    },
    {
      id: 2,
      idPortfolioList: 6,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606776535/portfolio/model/midnightgospel/sec_dktemn.jpg`,
      alt: 'Clancy from midnight gospel camera 2',
    },
    {
      id: 3,
      idPortfolioList: 6,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606776535/portfolio/model/midnightgospel/thrids_2_eflw2k.jpg`,
      alt: 'Clancy from midnight gospel camera 3',
    },
    {
      id: 1,
      idPortfolioList: 7,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606782015/portfolio/model/vasijas/vasijas_final_by9ztv.jpg`,
      alt: 'Still Life',
    },
    {
      id: 2,
      idPortfolioList: 7,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606782014/portfolio/model/vasijas/difusse_r9gtsc.jpg`,
      alt: 'Diffuse color. Arbitrary output variable',
    },
    {
      id: 3,
      idPortfolioList: 7,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606782021/portfolio/model/vasijas/wireframe_ydu3xw.jpg`,
      alt: 'Wireframe.',
    },
    {
      id: 4,
      idPortfolioList: 7,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606782014/portfolio/model/vasijas/gray_shade_g4xyt4.jpg`,
      alt: 'Clay',
    },
    {
      id: 5,
      idPortfolioList: 7,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606782015/portfolio/model/vasijas/lighting_vtskxm.jpg`,
      alt: 'Lighting',
    },
    {
      id: 6,
      idPortfolioList: 7,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606782016/portfolio/model/vasijas/uvs_ipbjks.jpg`,
      alt: 'UV UDIMS',
    },
    {
      id: 1,
      idPortfolioList: 8,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606859685/portfolio/model/kidmostro/kidmostro_camera1_g9mfjy.jpg`,
      alt: 'Kidmostro character',
    },
    {
      id: 2,
      idPortfolioList: 8,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606859684/portfolio/model/kidmostro/final_monster_2_ipyafx.jpg`,
      alt: 'kidmostro character camera 2',
    },
    {
      id: 3,
      idPortfolioList: 8,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606859685/portfolio/model/kidmostro/lighting_zrvf65.jpg`,
      alt: 'Kidmostro lighting',
    },
    {
      id: 4,
      idPortfolioList: 8,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606859685/portfolio/model/kidmostro/gray_xyaol6.jpg`,
      alt: 'Kidmostro gray shaded',
    },
    {
      id: 1,
      idPortfolioList: 9,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606862077/portfolio/model/huesos/huesos_final_smoke_s3v7l2.jpg`,
      alt: 'The grim adventures of billy & mandy character',
    },
    {
      id: 2,
      idPortfolioList: 9,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606862077/portfolio/model/huesos/diffuse_e5ke54.jpg`,
      alt: 'Diffuse color',
    },
    {
      id: 3,
      idPortfolioList: 9,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606862077/portfolio/model/huesos/lighting_m4rom0.jpg`,
      alt: 'Lighting',
    },
    {
      id: 4,
      idPortfolioList: 9,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606862078/portfolio/model/huesos/volume_sdysfj.jpg`,
      alt: 'Volume. Arbitrary output variable',
    },
    {
      id: 5,
      idPortfolioList: 9,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606862078/portfolio/model/huesos/gray_shade_fwnrem.jpg`,
      alt: 'Gray shaded. Arbitrary output variable',
    },
    {
      id: 6,
      idPortfolioList: 9,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606862078/portfolio/model/huesos/wireframe_xuw3as.jpg`,
      alt: 'Wireframe. Arbitrary output variable',
    },
    {
      id: 1,
      idPortfolioList: 10,
      src:
        'https://cdnb.artstation.com/p/assets/images/images/018/364/081/large/ivan-bautista-final-rein.jpg?1559095402',
      alt: 'Reinhardt character',
    },
    {
      id: 2,
      idPortfolioList: 10,
      src:
        'https://cdna.artstation.com/p/assets/images/images/018/364/080/large/ivan-bautista-final-pink-back.jpg?1559095400',
      alt: 'Reinhardt character camera 2',
    },
    {
      id: 3,
      idPortfolioList: 10,
      src:
        'https://cdna.artstation.com/p/assets/images/images/018/364/082/large/ivan-bautista-lighting.jpg?1559095405',
      alt: 'Reinhardt Lighting',
    },
    {
      id: 4,
      idPortfolioList: 10,
      src:
        'https://cdnb.artstation.com/p/assets/images/images/018/364/083/large/ivan-bautista-turnaround.jpg?1559095407',
      alt: 'Reinhardt turn around',
    },
    {
      id: 5,
      idPortfolioList: 10,
      src:
        'https://cdna.artstation.com/p/assets/images/images/018/829/690/large/ivan-bautista-nodes.jpg?1560887733',
      alt: 'Reinhardt texture nodes',
    },
    {
      id: 6,
      idPortfolioList: 10,
      src:
        'https://cdna.artstation.com/p/assets/images/images/018/830/804/large/ivan-bautista-uv.jpg?1560891207',
      alt: 'Reinhardt uv map udims',
    },
  ],
}

module.exports = { projectsDb }
