/*categories ->  1: frontend, 2: model*/
const PHOTO_EDIT = '/f_auto,dpr_auto,q_auto:good'
const projectsDb = {
  portfolioList: [
    {
      id: 1,
      title: 'SCORM COURSES',
      description: 'UI/UX & Frontend development',
      cover:
        'https://res.cloudinary.com/ivanrice-c/image/upload/q_auto:eco/v1597355406/portfolio/uiux_courses/cover_tvtvpb.jpg',
      category: 1,
      tools: ['css', 'html', 'php', 'jquery', 'bootstrap'],
    },
    {
      id: 2,
      title: 'FILE MANAGER',
      description: 'Php - Angular fullstack development',
      cover:
        'https://res.cloudinary.com/ivanrice-c/image/upload/q_auto:eco/v1597354705/portfolio/register/cover_jjaqkq.jpg',
      category: 1,
      tools: ['angular', 'html', 'php', 'css', 'bootstrap', 'mysql'],
    },
    {
      id: 3,
      title: 'SCHOOL MANAGER',
      description: 'React - php fullstack development',
      cover:
        'https://res.cloudinary.com/ivanrice-c/image/upload/q_auto:eco/v1597354032/portfolio/sigem/cover_iva5vx.jpg',
      category: 1,
      tools: ['react', 'html', 'php', 'css', 'bootstrap'],
    },
    {
      id: 4,
      title: 'VEHICLE INSURANCE',
      description: 'Webservice - lamp fullstack development',
      cover:
        'https://res.cloudinary.com/ivanrice-c/image/upload/q_auto:eco/v1597357629/portfolio/saas/cover_qhrryd.jpg',
      category: 1,
      tools: ['html', 'php', 'jquery', 'css', 'bootstrap', 'mysql'],
    },
    {
      id: 5,
      title: 'SPACE SHIP',
      description: 'A steampunk style & material practice',
      cover:
        'https://cdnb.artstation.com/p/assets/images/images/027/424/717/20200607002852/smaller_square/ivan-bautista-nave-final.jpg?1591507733',
      category: 2,
      tools: ['css', 'html', 'php', 'jquery', 'bootstrap'],
    },
    {
      id: 6,
      title: 'CLANCY',
      description: 'Clancy fan art from The midnight gospel',
      cover:
        'https://cdna.artstation.com/p/assets/images/images/030/401/790/smaller_square/ivan-bautista-clancy-w.jpg',
      category: 2,
      tools: ['css', 'html', 'php', 'jquery', 'bootstrap'],
    },
    {
      id: 7,
      title: 'STILL LIFE',
      description: 'A practice of lighting and materials',
      cover:
        'https://cdna.artstation.com/p/assets/images/images/018/363/916/smaller_square/ivan-bautista-vasijas-final.jpg',
      category: 2,
      tools: ['css', 'html', 'php', 'jquery', 'bootstrap'],
    },
    {
      id: 8,
      title: 'KID MOSTRO',
      description: 'A practice of fur grooming and lighting',
      cover:
        'https://cdnb.artstation.com/p/assets/images/images/018/831/139/smaller_square/ivan-bautista-kidmostro-camera1.jpg',
      category: 2,
      tools: ['css', 'html', 'php', 'jquery', 'bootstrap'],
    },
    {
      id: 9,
      title: 'GRIM REAPER',
      description: 'The grim fan art from Billy & Mandy',
      cover:
        'https://cdnb.artstation.com/p/assets/images/images/018/378/367/smaller_square/ivan-bautista-huesos-final-smoke.jpg',
      category: 2,
      tools: ['css', 'html', 'php', 'jquery', 'bootstrap'],
    },
    {
      id: 10,
      title: 'REINHARDT',
      description: 'Reinhardt fan art from overwatch',
      cover:
        'https://cdnb.artstation.com/p/assets/images/images/018/364/081/smaller_square/ivan-bautista-final-rein.jpg',
      category: 2,
      tools: ['css', 'html', 'php', 'jquery', 'bootstrap'],
    },
  ],
  img_items: [
    {
      id: 1,
      idPortfolioList: 1,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597279601/portfolio/uiux_courses/cover_aqvsdv.png`,
      alt: 'cover of the project',
    },
    {
      id: 2,
      idPortfolioList: 1,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597279608/portfolio/uiux_courses/projectbr_wv9la0.png`,
      alt: 'brief of the project',
    },
    {
      id: 3,
      idPortfolioList: 1,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597360813/portfolio/uiux_courses/unam_courses_x7mkaj.png`,
      alt: '',
    },
    {
      id: 4,
      idPortfolioList: 1,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597279605/portfolio/uiux_courses/inbursa_bknwnl.png`,
      alt: '',
    },
    {
      id: 5,
      idPortfolioList: 1,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597279612/portfolio/uiux_courses/unam_ujl4om.png`,
      alt: '',
    },
    {
      id: 6,
      idPortfolioList: 1,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597279596/portfolio/uiux_courses/comex_ia7mrj.png`,
      alt: '',
    },
    {
      id: 7,
      idPortfolioList: 1,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597279588/portfolio/uiux_courses/3daovs_sdnzoj.png`,
      alt: '',
    },
    {
      id: 8,
      idPortfolioList: 1,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597279594/portfolio/uiux_courses/AOV_ymvcx1.png`,
      alt: '',
    },
    {
      id: 1,
      idPortfolioList: 2,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597280118/portfolio/register/architecture_vep86k.png`,
      alt: '',
    },
    {
      id: 2,
      idPortfolioList: 2,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597280114/portfolio/register/about_vumanf.png`,
      alt: '',
    },
    {
      id: 3,
      idPortfolioList: 2,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597280122/portfolio/register/colors_ysnxdz.png`,
      alt: '',
    },
    {
      id: 4,
      idPortfolioList: 2,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597280128/portfolio/register/registro_idnisl.png`,
      alt: '',
    },
    {
      id: 5,
      idPortfolioList: 2,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597280131/portfolio/register/ticket_rzkzse.png`,
      alt: '',
    },
    {
      id: 6,
      idPortfolioList: 2,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597280112/portfolio/register/USER_lqcdjq.png`,
      alt: '',
    },
    {
      id: 1,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597279894/portfolio/sigem/sigem_xwozyi.png`,
      alt: '',
    },
    {
      id: 2,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597279865/portfolio/sigem/architectured_m0ffwk.png`,
      alt: '',
    },
    {
      id: 3,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597279890/portfolio/sigem/about_xuyysj.png`,
      alt: '',
    },
    {
      id: 4,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597279861/portfolio/sigem/about_b_qckna0.png`,
      alt: '',
    },
    {
      id: 5,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597279922/portfolio/sigem/wireframe_g6i7cv.png`,
      alt: '',
    },
    {
      id: 6,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597279976/portfolio/sigem/setup_n69ngw.png`,
      alt: '',
    },
    {
      id: 7,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597279969/portfolio/sigem/campus_eafcc8.png`,
      alt: '',
    },
    {
      id: 8,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597279973/portfolio/sigem/home_zfi6b8.png`,
      alt: '',
    },
    {
      id: 9,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597279981/portfolio/sigem/user_menu_icgmkc.png`,
      alt: '',
    },
    {
      id: 10,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597279960/portfolio/sigem/5users_gl3jjh.png`,
      alt: '',
    },
    {
      id: 11,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597279965/portfolio/sigem/6calendar_qystjo.png`,
      alt: '',
    },
    {
      id: 12,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597279902/portfolio/sigem/uiux_dashboard_yvenyu.png`,
      alt: '',
    },
    {
      id: 13,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597279877/portfolio/sigem/dashboard_jhjov7.png`,
      alt: '',
    },
    {
      id: 14,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597279911/portfolio/sigem/uiux_user_ij2sfs.png`,
      alt: '',
    },
    {
      id: 15,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597279885/portfolio/sigem/USER_kodeuq.png`,
      alt: '',
    },
    {
      id: 16,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597279906/portfolio/sigem/uiux_PDF_bnzrcq.png`,
      alt: '',
    },
    {
      id: 17,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597279881/portfolio/sigem/pdf_ah7uno.png`,
      alt: '',
    },
    {
      id: 18,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597279898/portfolio/sigem/SIGEMV1_wzrglw.png`,
      alt: '',
    },
    {
      id: 19,
      idPortfolioList: 3,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1597279857/portfolio/sigem/version1_dscq1h.png`,
      alt: '',
    },
    {
      id: 1,
      idPortfolioList: 4,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606946296/portfolio/saas/1_architexture_y0ozna.png`,
      alt: '',
    },
    {
      id: 2,
      idPortfolioList: 4,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606946297/portfolio/saas/qwe_jekbcq.png`,
      alt: '',
    },
    {
      id: 3,
      idPortfolioList: 4,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606946296/portfolio/saas/3_color_cx99ka.png`,
      alt: '',
    },
    {
      id: 4,
      idPortfolioList: 4,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606946296/portfolio/saas/4_UIUX_gweaqf.png`,
      alt: '',
    },
    {
      id: 5,
      idPortfolioList: 4,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606946297/portfolio/saas/portada_ptdqss.jpg`,
      alt: '',
    },
    {
      id: 6,
      idPortfolioList: 4,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606946297/portfolio/saas/menu_g0dsid.jpg`,
      alt: '',
    },
    {
      id: 7,
      idPortfolioList: 4,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606946296/portfolio/saas/cotizacion_shbwlb.jpg`,
      alt: '',
    },
    {
      id: 8,
      idPortfolioList: 4,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606946296/portfolio/saas/mensaje_hjigrw.jpg`,
      alt: '',
    },
    {
      id: 9,
      idPortfolioList: 4,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606946296/portfolio/saas/consulta_b3fgmm.jpg`,
      alt: '',
    },
    {
      id: 1,
      idPortfolioList: 5,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606775187/portfolio/model/nave-final_v6m09q.jpg`,
      alt: '',
    },
    {
      id: 2,
      idPortfolioList: 5,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606774993/portfolio/model/SPEC_dgjnox.jpg`,
      alt: '',
    },
    {
      id: 3,
      idPortfolioList: 5,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606774992/portfolio/model/DIFFUSE_bhdjqm.jpg`,
      alt: '',
    },
    {
      id: 4,
      idPortfolioList: 5,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606774994/portfolio/model/emission_qyjzyw.jpg`,
      alt: '',
    },
    {
      id: 5,
      idPortfolioList: 5,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606774993/portfolio/model/LIGHT_uu7hiw.jpg`,
      alt: '',
    },
    {
      id: 6,
      idPortfolioList: 5,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606774993/portfolio/model/UVMAP_utl350.jpg`,
      alt: '',
    },
    {
      id: 7,
      idPortfolioList: 5,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606775523/portfolio/model/ivan-bautista-wip2_hd2o1r.jpg`,
      alt: '',
    },
    {
      id: 1,
      idPortfolioList: 6,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606776535/portfolio/model/midnightgospel/final_img_c_mzsgrf.jpg`,
      alt: '',
    },
    {
      id: 2,
      idPortfolioList: 6,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606776535/portfolio/model/midnightgospel/sec_dktemn.jpg`,
      alt: '',
    },
    {
      id: 3,
      idPortfolioList: 6,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606776535/portfolio/model/midnightgospel/thrids_2_eflw2k.jpg`,
      alt: '',
    },
    {
      id: 1,
      idPortfolioList: 7,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606782015/portfolio/model/vasijas/vasijas_final_by9ztv.jpg`,
      alt: '',
    },
    {
      id: 2,
      idPortfolioList: 7,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606782014/portfolio/model/vasijas/difusse_r9gtsc.jpg`,
      alt: '',
    },
    {
      id: 3,
      idPortfolioList: 7,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606782021/portfolio/model/vasijas/wireframe_ydu3xw.jpg`,
      alt: '',
    },
    {
      id: 4,
      idPortfolioList: 7,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606782014/portfolio/model/vasijas/gray_shade_g4xyt4.jpg`,
      alt: '',
    },
    {
      id: 5,
      idPortfolioList: 7,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606782015/portfolio/model/vasijas/lighting_vtskxm.jpg`,
      alt: '',
    },
    {
      id: 6,
      idPortfolioList: 7,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606782016/portfolio/model/vasijas/uvs_ipbjks.jpg`,
      alt: '',
    },
    {
      id: 1,
      idPortfolioList: 8,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606859685/portfolio/model/kidmostro/kidmostro_camera1_g9mfjy.jpg`,
      alt: '',
    },
    {
      id: 2,
      idPortfolioList: 8,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606859684/portfolio/model/kidmostro/final_monster_2_ipyafx.jpg`,
      alt: '',
    },
    {
      id: 3,
      idPortfolioList: 8,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606859685/portfolio/model/kidmostro/lighting_zrvf65.jpg`,
      alt: '',
    },
    {
      id: 4,
      idPortfolioList: 8,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606859685/portfolio/model/kidmostro/gray_xyaol6.jpg`,
      alt: '',
    },
    {
      id: 1,
      idPortfolioList: 9,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606862077/portfolio/model/huesos/huesos_final_smoke_s3v7l2.jpg`,
      alt: '',
    },
    {
      id: 2,
      idPortfolioList: 9,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606862077/portfolio/model/huesos/diffuse_e5ke54.jpg`,
      alt: '',
    },
    {
      id: 3,
      idPortfolioList: 9,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606862077/portfolio/model/huesos/lighting_m4rom0.jpg`,
      alt: '',
    },
    {
      id: 4,
      idPortfolioList: 9,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606862078/portfolio/model/huesos/volume_sdysfj.jpg`,
      alt: '',
    },
    {
      id: 5,
      idPortfolioList: 9,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606862078/portfolio/model/huesos/gray_shade_fwnrem.jpg`,
      alt: '',
    },
    {
      id: 6,
      idPortfolioList: 9,
      src: `https://res.cloudinary.com/ivanrice-c/image/upload${PHOTO_EDIT}/v1606862078/portfolio/model/huesos/wireframe_xuw3as.jpg`,
      alt: '',
    },
    {
      id: 1,
      idPortfolioList: 10,
      src:
        'https://cdnb.artstation.com/p/assets/images/images/018/364/081/large/ivan-bautista-final-rein.jpg?1559095402',
      alt: '',
    },
    {
      id: 2,
      idPortfolioList: 10,
      src:
        'https://cdna.artstation.com/p/assets/images/images/018/364/080/large/ivan-bautista-final-pink-back.jpg?1559095400',
      alt: '',
    },
    {
      id: 3,
      idPortfolioList: 10,
      src:
        'https://cdna.artstation.com/p/assets/images/images/018/364/082/large/ivan-bautista-lighting.jpg?1559095405',
      alt: '',
    },
    {
      id: 4,
      idPortfolioList: 10,
      src:
        'https://cdnb.artstation.com/p/assets/images/images/018/364/083/large/ivan-bautista-turnaround.jpg?1559095407',
      alt: '',
    },
    {
      id: 5,
      idPortfolioList: 10,
      src:
        'https://cdna.artstation.com/p/assets/images/images/018/829/690/large/ivan-bautista-nodes.jpg?1560887733',
      alt: '',
    },
    {
      id: 6,
      idPortfolioList: 10,
      src:
        'https://cdna.artstation.com/p/assets/images/images/018/830/804/large/ivan-bautista-uv.jpg?1560891207',
      alt: '',
    },
  ],
}

module.exports = { projectsDb }
